server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gym?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: wjffwj
  mvc:
    view:
      prefix: /
      suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml